name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# TAMBAHKAN BLOK INI
permissions:
  contents: write # Memberi izin untuk menulis ke repositori (push)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... (langkah-langkah checkout, generate snake tetap sama) ...

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: kimearwud22
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
